In [1]:
import pandas as pd
import numpy as np

In [ ]:
df_aop=pd.read_csv(
    r'../data/raw/2025-10-09-comagri-communes-aires-ao.csv',
    sep=';',
    encoding='latin1'
)

In [13]:
df_aop.head()

,CI,Département,Commune,Art,Aire géographique,IDA
0,01001,AIN,Abergement-Clémenciat,(L'),Beurre de Bresse,2225
1,01001,AIN,Abergement-Clémenciat,(L'),Crème de Bresse,2339
2,01001,AIN,Abergement-Clémenciat,(L'),Dinde de Bresse,1498
3,01001,AIN,Abergement-Clémenciat,(L'),"Volaille de Bresse ou poulet de Bresse, poular...",1959
4,01002,AIN,Abergement-de-Varey,(L'),Bugey,1597

In [16]:
df_aop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65484 entries, 0 to 65483
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CI                 65484 non-null  object
 1   Département        65484 non-null  object
 2   Commune            65484 non-null  object
 3   Art                4597 non-null   object
 4   Aire géographique  65484 non-null  object
 5   IDA                65484 non-null  int64
dtypes: int64(1), object(5)
memory usage: 3.0+ MB

In [22]:
df_aop.rename(columns={
    'CI': 'CP',
    'Aire géographique':'AOC/AOP',
})

,CP,Département,Commune,Art,AOC/AOP,IDA
0,01001,AIN,Abergement-Clémenciat,(L'),Beurre de Bresse,2225
1,01001,AIN,Abergement-Clémenciat,(L'),Crème de Bresse,2339
2,01001,AIN,Abergement-Clémenciat,(L'),Dinde de Bresse,1498
3,01001,AIN,Abergement-Clémenciat,(L'),"Volaille de Bresse ou poulet de Bresse, poular...",1959
4,01002,AIN,Abergement-de-Varey,(L'),Bugey,1597
...,...,...,...,...,...,...
65479,89484,YONNE,Volgré,NaN,Coteaux Bourguignons,2186
65480,89484,YONNE,Volgré,NaN,Crémant de Bourgogne,2399
65481,89484,YONNE,Volgré,NaN,Fine de Bourgogne,1947
65482,89484,YONNE,Volgré,NaN,Marc de Bourgogne,1946
65483,89486,YONNE,Yrouerre,NaN,Chaource,1466

In [27]:
df_aop=df_aop.drop(columns='Art')

In [28]:
df_aop.to_csv(
    r'../data/processed/aop.csv' 
    )